apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: zeus
  name: zeus
  namespace: prometheus
spec:
  podMetricsEndpoints:
    - interval: 5s
      path: /
      port: metrics
  selector:
    matchLabels:
      app: register-node